version: '3.4'

services:
  react-client:
    image: react-client-image
    build:
      context: react-app
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  api: # http://localhost:5000/swagger/index.html
    image: api-app
    build:
      context: api-app/MainApi
      dockerfile: MainApi/Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    container_name: container.local.pg
    image: postgres:latest
    ports:
      - "5432:5432" # 5432:80
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      # POSTGRES_DB: "my_db"
      # POSTGRES_USER: "my_user"
      POSTGRES_PASSWORD: 123456
